### ISSUE TITLE
AS keyword within sql statement not working

### ISSUE THREAD

**Issue by sintaq83** [mantisbt-plugins/Query#1]
hi @CasN 

At the Field Definition for Output Query, when i try to use AS keyword, the field's value is not populate accordingly. However, if I remove the AS keyword, the value populate just fine.

Sample my query statement: from_unixtime(bugtable.last_updated) AS UpdateOn

DB: MariaDB
Type: Query
User/Admin: User

**Comment by ghost** [comment]
Hi Sintaq83, are you creating a query or a script? It seems to be caused by the function somehow. I need to do some more testing. If you use a field with out function, the keyword works perfectly.

**Comment by sintaq83** [comment]
Hi Cas,
Its a query

**Comment by ghost** [comment]
It will work as long as you do not use capitals in the AS-value.
So "from_unixtime(last_updated) as updated_on" will work fine where  "from_unixtime(last_updated) as Updated_on" will fail.
Have not yet been able to find out why that is. I keep thinking about it but at least for now you know how to deal with this.

**Comment by sintaq83** [comment]
Hi @CasN

I can confirmed your resolution works. Weird 😅

Anyway, thanks for your swift help

**Comment by dregad** [comment]
> Have not yet been able to find out why that is.

This is because MantisBT database API [forces column names to lowercase](https://github.com/mantisbt/mantisbt/blob/319915c56d9025db91c5b001c2604a3432fa4557/core/database_api.php#L62)

So you need to apply strtolower here
https://github.com/mantisbt-plugins/Query/blob/6d34d1118f19445b5a6803b63c4b434d02ee3547/pages/exec_query.php#L108

**Comment by ghost** [comment]
Updated this in version 2.15

**Comment by dregad** [comment]
Not fixed.

I meant
`$content .= $row2[strtolower( trim( $name ) )] ;`

**Comment by ghost** [comment]
Changed accordingly in version 2.16

**Comment by dregad** [comment]
Tested OK
