### ISSUE TITLE
Why are there log files in the repository ?

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/Query#10]
See https://github.com/mantisbt-plugins/Query/tree/main/pages/logs. In my opinion, these should be removed.

They are probably leftovers from executing this:
https://github.com/mantisbt-plugins/Query/blob/6d34d1118f19445b5a6803b63c4b434d02ee3547/pages/exec_schedule.php#L8-L11

Which IMO is bad practice - you should not be storing log files in the MantisBT directory (a normally configured web server would most likely not have write access here).

You should have a config to specify the directory to save log files, or store the logs in a DB table (1:M child to *schedule* table).

**Comment by ghost** [comment]
In version 2.15, i have moved these to another location.
