### ISSUE TITLE
Error when trying to configure the sheduller

### ISSUE THREAD

**Issue by ZakharchukEduard** [mantisbt-plugins/Query#2]
Hi. 
You make incredibly useful plugins for Mantis. 
Thank you so much.
There is an error when trying to configure the sheduller.
I'm filling in these fields.

![изображение](https://github.com/mantisbt-plugins/Query/assets/34164109/50d42c26-48fd-4ee8-b567-8b8e15d9018f)

When you click on the “Add definition” button, an error appears:

![изображение](https://github.com/mantisbt-plugins/Query/assets/34164109/c5253817-42f0-4959-a4b3-f4b6a629d708)

Probably need to configure the plugin correctly. 
Can you tell me what should be configured?

**Comment by ghost** [comment]
is resolved in version 2.13

**Comment by ZakharchukEduard** [comment]
Hi. Thanks for the very quick response and fixing the error.
