### ISSUE TITLE
When I save script I get an error

### ISSUE THREAD

**Issue by ZakharchukEduard** [mantisbt-plugins/Query#3]
Hi. I can't seem to use your plugin. I get errors.
I'm trying to create a test script and when I save it I get an error.

That's the setting
![изображение](https://github.com/mantisbt-plugins/Query/assets/34164109/5205870f-a7c4-4c6e-af4c-55add0b5661f)

That's the error
![изображение](https://github.com/mantisbt-plugins/Query/assets/34164109/adb364d2-5ba5-4c42-8ffe-92278d16647d)

**Comment by ghost** [comment]
Attach your script to the issue and I will investigate/fix on Monday. This weekend I am out on the motorbike😁

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: ZakharchukEduard ***@***.***>
Sent: Friday, May 10, 2024 12:51:17 PM
To: mantisbt-plugins/Query ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mantisbt-plugins/Query] When I save script I get an error (Issue #3)


Hi. I can't seem to use your plugin. I get errors.
I'm trying to create a test script and when I save it I get an error.

That's the setting
default.png (view on web)<https://github.com/mantisbt-plugins/Query/assets/34164109/5205870f-a7c4-4c6e-af4c-55add0b5661f>

That's the error
default.png (view on web)<https://github.com/mantisbt-plugins/Query/assets/34164109/adb364d2-5ba5-4c42-8ffe-92278d16647d>

**Comment by ZakharchukEduard** [comment]
This error appears any time you try to add a script or query.
I'm in no hurry. This error doesn't interfere with my work. 
It's for the future I want to customize a couple of scripts.

**Comment by ghost** [comment]
This is not how it works. In the first step you only define the query. Next you click on Edit once your definition is in the list. There you put your code to be executed. Please share your code so I can check if this will be working (what I now see of the code does not look ok).

**Comment by ghost** [comment]
Also download version 2.13, there are some improvements. In case you use php 8.2, plase see the readme.

**Comment by ZakharchukEduard** [comment]
Hi. 
Yes I have plugin version 2.13 and PHP version 8.3.
I reread the readme  file, found the ADORecordSet_mysqli class in the code and I don't understand what I should replace.
Can you please describe it in more detail?
![изображение](https://github.com/mantisbt-plugins/Query/assets/34164109/aada2007-cdc0-4f51-a381-057df684913a)

**Comment by ghost** [comment]
add the following line:
#[AllowDynamicProperties]

right before:
class ADORecordSet_mysqli extends ADORecordSet{

**Comment by ZakharchukEduard** [comment]
I add line.
![изображение](https://github.com/mantisbt-plugins/Query/assets/34164109/1a14d3d4-d645-4673-a271-1727e326b0a8)

I try to add a new script.
![изображение](https://github.com/mantisbt-plugins/Query/assets/34164109/b8ca37d6-f67d-4e72-b84e-959e5e283748)

And still get an error.
![изображение](https://github.com/mantisbt-plugins/Query/assets/34164109/cf72d50e-f55d-45c7-b0ae-55910c3acec7)

**Comment by ghost** [comment]
please download query_add.php and edit_schedule2.php again and load to your webserver. Is should work now.

**Comment by ZakharchukEduard** [comment]
I reinstalled the plugin completely. 
When I try to add a script I get a new error:



```
APPLICATION ERROR #401

Database query failed. Error received from database was #1364: Field 'query_script' doesn't have a default value for the query: INSERT INTO mantis_plugin_Query_definitions_table ( query_name,query_type,query_lvl,query_desc ) VALUES ( 'test','S', 'A','test').
Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.
```

**Comment by ghost** [comment]
That is strange, can you check the definition of the mantis_plugin_Query_definitions_table ? It should have default values, see image:
![image](https://github.com/mantisbt-plugins/Query/assets/7385748/d7735cb7-cbb1-4572-948d-9d1aa76be2ce)

**Comment by ZakharchukEduard** [comment]
The default value has not been filled in.
After filling it in, I was able to add the script to the list.
Thanks for the tip.

**Comment by ghost** [comment]
Version 2.15 is on the way with a number additional improvements
