### ISSUE TITLE
Query Name should be unique

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/Query#7]
Right now the plugin allows creating multiple Queries with the same name, so later it becomes difficult to know which is which, e.g. in the query selection list when creating a new schedule

![image](https://github.com/mantisbt-plugins/Query/assets/449891/ba4e0026-5571-44f2-9186-2499f2c33e99)

**Comment by ghost** [comment]
Is now checked as of version 2.15

**Comment by dregad** [comment]
It's OK when creating a new definition, but not tested when updating, so I can rename a definition to an already existing name.

**Comment by ghost** [comment]
Ha nice catch, forgot that situation since earlier is was not possible to update the name. This will be fixed in 2.17
