### ISSUE TITLE
User interface needs improvement

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/Query#9]
Plugin is generally not conforming to MantisBT standard. 

There a lot of things to say here and I don't have so much time to write it all up, but here are a few things to get you started

- Layout of *user_query* page
![image](https://github.com/mantisbt-plugins/Query/assets/449891/b5b4f7de-a4cb-4b2e-9482-1d5c723e1be4)
- It would be nice, if user is allowed, to have a button/link to go to configuration page
- Query menu in sidebar is not highlighed when page is active
- Same for Tab on Manage pages
- Consider using sub-menus for the 3 config pages (see adm_permissions_report.php). Then you can remove the `
Configuration <==> Maintain Schedules` header which looks kind of weird
- buttons styling is wrong
- use buttons instead of plain links, e.g.
![image](https://github.com/mantisbt-plugins/Query/assets/449891/0cbaaf1d-e8a6-4d64-ba7d-7aabc976b244)
- Use a separate section to add new Definitions / Schedules and to list existing ones
- Instead of defining custom User/Admin (`U`/`A`) levels for restricted queries, why not simply use a standard Access Level threshold ?

Is there really an added value to split a query into 6 distinct fields, instead of using a single, larger textarea ? It makes maintenance unnecessarily complex, as you can't just copy/paste the query from your favorite SQL tool.

Edit Query screen layout is kind of weird with label above textarea and help text on the left, I think it would be better to have more standard layout with label on left and input field on the right, with help text either below the label, or above / below the input field (lookt at Source Integration plugin config page for example).

**Comment by ghost** [comment]
I have no clue where the highlighting is handled in the sidebar.
Now there is an option to have one field to hold the full query (which was already there behind the scenes). When using this option, I can (currently) not support additional filters while scheduling. Most of the points I will handle in the very near future:)

**Comment by dregad** [comment]
> I have no clue where the highlighting is handled in the sidebar.

On second thoughts I'm not sure the Core API actually allows this. Need to check.

**Comment by ghost** [comment]
Almost all changes are embedded in version 2.16 with the exception of:
- Use a separate section to add new Definitions / Schedules and to list existing ones
   I prefer this lay-out since you also see what is there before adding something 
- Instead of defining custom User/Admin (U/A) levels for restricted queries, why not simply use a standard Access Level threshol ?
   I use this level to decide which queries can go in the user list. But do think it is better to change to standard levels. So this will 
  end up in the next version.

**Comment by dregad** [comment]
>> Use a separate section to add new Definitions / Schedules and to list existing ones
>
> I prefer this lay-out since you also see what is there before adding something

With this reasoning it would be more logical to have the Add section at the end of the list, which is not so different from what I'm suggesting (e.g. manage_prof_menu_page.php).

Anyway it's your plugin so do as you want, I'm just saying 😉 

> do think it is better to change to standard levels. So this will end up in the next version.

👍

**Comment by dregad** [comment]
Looks much nicer now, thanks !

Some more comments

![image](https://github.com/mantisbt-plugins/Query/assets/449891/8c1ad584-d59d-47cb-b3a0-691d0775480f)

- It would be more logical to have *Maintain Queries* listed before *Maintain Schedules*
- A bit confusing to display the button to go the currently active page
- Consider hiding or disable *Maintain Schedules* button when there are no defined queries
- Add a space between buttons

Suggest using smaller Action buttons (`btn-xs` class) as shown in screenshot below.

![image](https://github.com/mantisbt-plugins/Query/assets/449891/b058c291-7d8d-4f35-8155-cb02a7c5c711)

**Comment by ghost** [comment]
All available in verrsion 2.18 (thanks for helping out to get all in line).
